doc: Add translation for Simplified Chinese(zh-CN)
nvh95/vitest-preview pull request #19
Opened 2023-01-05 10:15 UTC by RiverTwilight

## Summary/ Motivation (TLDR;)

Translation for zh-CN.

2023-01-05 13:17 UTC, jsun969 commented on website/docs/zh/guide/vue-test-utils.md
> +See more at <https://github.com/nvh95/vitest-preview/tree/main/examples/vue-test-utils>
Here is a missing translation

2023-01-05 13:27 UTC, jsun969 requested changes
Is `/.vitepress/cache/deps` a runtime folder? I assume it should be removed.

2023-01-05 13:27 UTC, jsun969 commented on website/docs/zh/index.md
> +  tagline: 调试 Vitest 测试，如此简单。 🧪🖼⚡️
```suggestion
  tagline: 轻松地调试 Vitest 测试。 🧪🖼⚡️
```

2023-01-05 13:27 UTC, jsun969 commented on website/docs/zh/guide/vue-test-utils.md
> +See more at <https://github.com/nvh95/vitest-preview/tree/main/examples/vue-test-utils>
Here is a missing translation

2023-01-05 13:27 UTC, jsun969 commented on website/docs/zh/index.md
> +  - title: '体验优先'
```suggestion
  - title: 'DX驱动'
```

2023-01-05 13:27 UTC, jsun969 commented on website/docs/zh/index.md
> +    details: Vitest Preview 能帮助你更快更轻松地建立测试。 你的应用也会有更好的可靠性和拓展性。
```suggestion
    details: Vitest Preview 能帮助你更快更轻松地建立测试。你的应用也会有更好的可靠性和拓展性。
```

2023-01-05 13:27 UTC, jsun969 commented on website/docs/guide/getting-started.zh-CN.md
> +dfasf
???

2023-01-05 13:27 UTC, jsun969 commented on website/docs/.vitepress/config.ts
> +function sidebarGuide_zhCN() {
```suggestion
function sidebarGuideCN() {
```

2023-01-05 13:27 UTC, jsun969 commented on website/docs/.vitepress/config.ts
> +      '/zh/guide/': sidebarGuide_zhCN()
```suggestion
      '/cn/guide/': sidebarGuideCN()
```

2023-01-05 13:27 UTC, jsun969 commented on website/docs/.vitepress/config.ts
> +    '/zh/': {
```suggestion
    '/cn/': {
```

2023-01-05 13:31 UTC, jsun969 commented
Use pnpm instead of yarn

2023-01-05 13:55 UTC, jsun969 requested changes

2023-01-05 13:55 UTC, jsun969 commented on website/docs/guide/svelte-testing-library.md
> +参见 <https://github.com/nvh95/vitest-preview/tree/main/examples/svelte-testing-library>
This is the origin doc

2023-01-05 14:09 UTC, RiverTwilight commented
All addressed. Thanks! @jsun969

2023-01-05 14:09 UTC, jsun969 approved these changes

2023-01-08 13:18 UTC, nvh95 approved these changes
LGTM!

2023-01-08 13:18 UTC, merged

2023-01-08 13:19 UTC, nvh95 commented
@RiverTwilight Thank you very much for your time invested in `vitest-preview` 🥰
@jsun969 Thanks for your help in reviewing this PR.

2023-01-08 13:20 UTC, nvh95 commented
@all-contributors please add @RiverTwilight for translation

2023-04-24 06:49 UTC, nvh95 commented
Hi @RiverTwilight @jsun969. I just found out that the merge commit hasn't been deployed to production. I just cleared cache and manually deploy the Chinese version of the docs. You can check it out at https://www.vitest-preview.com/zh/

Again. Thank you for your help 🎉.